### PR TITLE
Did it send? BotServ Enhancement

### PR DESCRIPTION
**Pull request by AlphaT3ch**
Some may say this is pointless, but I think it adds a good touch. When using "/bs say" or "/bs action" it will tell the user via notice if the message has sent instead of just staring into blank nothing. Some newer users may think the services are broken when they're just not checking the right tab.

->BotServ<- say #Test This is a test!
<ChanServ> This is a test!
-BotServ- Sent message to channel

### CODE REVIEW

**Comment by Zoddo** [comment]
I think it will flood the sender than anything else.

The user know in what channel it sends the message.

**Comment by Adam-** [comment]
I'd be okay with this only if the user doing the sending isn't in the channel.

**Comment by Zoddo** [comment]
Or allow to disable this notice.

**Comment by AlphaT3ch** [comment]
@Adam- That's possible? Doing "!help say" says that there is no help for that command (therefor not a command)

**Comment by del6597** [comment]
@AlphaT3ch there is help for the SAY command.  You can get the help by messaging BotServ help say.
Syntax: SAY _channel_ _text_
"Makes the bot say the specified text on the specified channel."

**Comment by AlphaT3ch** [comment]
@del6567 And?

**Pull request closed without merging**
