### PR TITLE
win32.rc error RC2127

### PR DESCRIPTION
**Pull request by Zageron**
CMake broke as of this commit, the win32.rc was reporting incorrect versions with error RC2127 : version WORDs separated by commas expected. This is definitely not a solution, but the easiest way to report the issue. As of now building on Windows is blocked.

The area in question reports:
VER_ANOPE VERSIONINFO
 FILEVERSION ,,,0
 PRODUCTVERSION ,,,0

Rather than
VER_ANOPE VERSIONINFO
 FILEVERSION 2,0,2,0
 PRODUCTVERSION 2,0,2,0

### CODE REVIEW

**Comment by Zageron** [comment]
So given the failure of the build, I'd say a different approach will need to be taken to solve this. I'm not familiar with CMake, so I do not know how to resolve it. Cheers,

**Comment by Adam-** [comment]
This commit is okay, the Windows specific build system code has not been updated to cope with this new change is all.

**Comment by Zageron** [comment]
Alright, good to know. I'll keep my eye open for the build system updates, thank you for the speedy response. :)

**Comment by Adam-** [comment]
This is fixed now.

**Pull request closed without merging**
