### PR TITLE
Added kickcheck override for users with protected privs

### PR DESCRIPTION
**Pull request by H7-25**
I think should be useful having this override for users with protected privs (Can not be kicked from channels by Services)

### CODE REVIEW

**Comment by Adam-** [comment]
Probably just u->isProtected()

**Comment by H7-25** [comment]
i don't see isProtected() in user class ..

**Comment by Adam-** [comment]
I meant IsProtected

**Comment by Adam-** [comment]
Squash this

**Comment by H7-25** [comment]
Squashed :+1:

**Comment by Adam-** [comment]
I don't know why you want this, this is redundant due to https://github.com/anope/anope/blob/2.0/src/channels.cpp#L896.

**Pull request merged**
