### PR TITLE
Updated Travis build process for Anope 2.1 Redux

### PR DESCRIPTION
**Pull request by KeiroD**
It took a fair amount of time to get a working process for Travis CI to build Anope 2.1 successfully.

Mostly because I was not successfully getting gcc to install. But now we're pretty good to go. If nothing else, it's good to have a method for checking your code works... after all, you guys have it for Anope 2.x.

Also, apologies on the notifications server, that should be corrected for you guys, now.

### CODE REVIEW

**Comment by SaberUK** [comment]
1. You should rebase your repository so theres only one commit.

2. Why can't you just use [trusty](https://docs.travis-ci.com/user/trusty-ci-environment/) instead of backports for precise?

**Comment by KeiroD** [comment]
@SaberUK Because I could not get it to work due to the way Travis CI works. If you check out [this issue for GCC](https://github.com/travis-ci/travis-ci/issues/1379) which has links to several other things that has a great deal more information about how Travis CI itself handles GCC and CMake.

As to your second point, I'll rebase my repository and then produce the commit as you requested. Should I close this one and open a new one once I've done that?

**Comment by KeiroD** [comment]
Gah! I thought I'd rebased this thing correctly! :|

**Comment by KeiroD** [comment]
Gonna just redo the entire repository because I apparently cannot brain how do rebase.

**Pull request closed without merging**
