### PR TITLE
Update ngircd protocol module

### PR DESCRIPTION
**Pull request by KoraggKnightWolf**
It appears the ngircd protocol module was lacking the +N channel mode for no nick changes (originally encountered by Kayejyu2/S3xyL1nux on irc.anope.org #anope). Upon further investigation I noticed that some other user modes were missing, and that one, the umode (not channel mode) +b was misnamed as NOCTCP when the docs state it disallows PRIVMSG/NOTICE. 
For the alteration I am referring to https://github.com/ngircd/ngircd/blob/master/doc/Modes.txt 
If anyone has better naming suggestions, please feel free to use those instead, this is just a basic idea on how to make the module up go date.

Regards,

Koragg

### CODE REVIEW

**Comment by KoraggKnightWolf** [comment]
Fixed a typo in the umode name so that it now spells out CONNECT_NOTICE as it should for umode +c

**Comment by KoraggKnightWolf** [comment]
The doc states this about umode +c: IRC operator wants to receive connect/disconnect NOTICEs. So I figured CONNECT_NOTICE might be a solid name. If not, what would other suggestions be that are clearer?

Regards,

Koragg

**Comment by alexbarton** [comment]
Looks good to me, thank you!

**Comment by Adam-** [comment]
This access list change should definitely *not* be part of this PR

**Comment by KoraggKnightWolf** [comment]
Closed due to my own mistake of not creating a branch for my own customizations and clogging up the PR. Sincerest apologies it was not intentional.

Regards,

Koragg

**Pull request closed without merging**
