### PR TITLE
cs_entrymsg to use SET permission, not isFounder

### PR DESCRIPTION
**Pull request by flotwig**
Makes the ability to control ENTRYMSG's assignable instead of restricted to only the channel founder.

### CODE REVIEW

**Comment by flotwig** [comment]
Okay, I'm a little lost here. I don't know C++ to fix this, but now it says the list is full whenever trying to add a new ENTRYMSG. Someone want to point out the problem?

**Comment by Adam-** [comment]
You have entrymsg:maxentries set to 0.

**Comment by flotwig** [comment]
It's set to 5, ENTRYMSG worked (only for founder) before this change. That's why it's perplexing.

**Comment by flotwig** [comment]
Patch works correctly, it was an error on our side for having the module renamed. Everything is a-ok.

**Comment by Adam-** [comment]
Can you squash this?

**Comment by flotwig** [comment]
There you go.

**Pull request merged**
